fix: revert lighthouse and fix tests

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -48,6 +48,23 @@ jobs:
           grep 'success: false' check_report
           grep "Element 'body' does not contain 'No Way'" check_report
 
+      - name: test check lighthouse
+        run: |
+          set +e
+            PURR_CONFIG_CONCURRENCY=1 \
+            PURR_CONFIG_TRACES=false \
+            PURR_CONFIG_CHROMIUM_REMOTE_DEBUGGING=true \
+            PURR_CONFIG_BROWSER_HEADLESS=false \
+            ./src/cli.js check --no-shorten \
+            example-com-lighthouse > check_report
+          code=$?
+          set -e
+          cat check_report
+          [ $code -eq 1 ] && echo 'Error: Check should succeed' && exit 1
+          grep 'success: true' check_report
+          grep "labels: { name: 'first-contentful-paint', id: 'lh-one' }" \
+            check_report
+
       - name: 'lint configs'
         run: yarn prettier -c 'data/*'
 
